### ISSUE TITLE
Metric for backup count per datastore

### ISSUE THREAD

**Issue by ntimo** [rare-magma/pbs-exporter#1]
Hello,
I just found this awesome project and wanted to ask if it possible to add a metric that contains the backup counts per datastore or maybe even per vm id in the data store.

Thanks for creating this

**Comment by rare-magma** [comment]
Hello,
It should be possible to add such a metric, it would involve doing a new API request to the /api2/json/admin/datastore/{store}/snapshots endpoint as described in: https://pbs.proxmox.com/docs/api-viewer/index.html#/admin/datastore/{store}/snapshots and parse the response

**Comment by rare-magma** [comment]
Hello,

I've added a couple of new metrics:
"pbs_snapshot_count" which tracks the backup counts per datastore
"pbs_snapshot_vm_count"  which tracks the backup counts per vm per datastore
