### ISSUE TITLE
pbs_snapshot_vm_count error metric: "pushed metrics are invalid or inconsistent with existing metrics"

### ISSUE THREAD

**Issue by ntimo** [rare-magma/pbs-exporter#2]
Hello,
I just updated to the new version with snapshot metrics and now when I run the exporter I get this error:

```
an 07 16:32:33 pbs pbs_exporter.sh[196541]: pushed metrics are invalid or inconsistent with existing metrics: 7 error(s) occurred:
Jan 07 16:32:33 pbs pbs_exporter.sh[196541]: * collected metric "pbs_snapshot_vm_count" { label:<name:"host" value:"pbs" > label:<name:"instance" value:"" > label:<name:"job" value:"pbs_exporter" > label> was collected before with the same name and label values
Jan 07 16:32:33 pbs pbs_exporter.sh[196541]: * collected metric "pbs_snapshot_vm_count" { label:<name:"host" value:"pbs" > label:<name:"instance" value:"" > label:<name:"job" value:"pbs_exporter" > label> was collected before with the same name and label values
```

**Comment by rare-magma** [comment]
Hello,
That's probably caused by the fact that I changed the help strings in the previous metrics on https://github.com/rare-magma/pbs-exporter/commit/f347807ff7784b4bf85831c9815a96404d62eeb6#diff-f5b3d9f36c2a7cb07f6f1ac3edc333ad47c4df1fabd68b4b0a0609390dd25a52R48 to better reflect the new logic (ignore datastores in maintenance mode)
The pushgateway will throw warnings like the ones you're seeing in the log when that happens. 
To get rid of the warnings, I think it will be necessary to delete the metrics in the pushgateway to avoid the conflict between old and new help strings.

**Comment by ntimo** [comment]
I stopped my pushgateway container and started it again, I then manually run the pbs exporter service but the same error is returned on a completely empty pushgateway.

**Comment by rare-magma** [comment]
I think it might be necessary to manually delete the job in the pushgateway UI, perhaps just restarting the container won't clear them.

**Comment by rare-magma** [comment]
Or actually it might be caused by two VMs having the same id, could you please check if that's the case in your system?

**Comment by ntimo** [comment]
Yes I have two VMs with the same id that are in different datastores, so this should actually be fine.

> Or actually it might be caused by two VMs having the same id, could you please check if that's the case in your system?

**Comment by ntimo** [comment]
> I think it might be necessary to manually delete the job in the pushgateway UI, perhaps just restarting the container won't clear them.

To clarify I stopped the container deleted it and recreated it. Since the pushgateway has no persistent storage, it was completely empty

**Comment by rare-magma** [comment]
It might be easier to understand what is going on by getting the following output:
run the script with 
`bash -x ./pbs_exporter | grep 'pbs_snapshot_vm_count'`

**Comment by rare-magma** [comment]
> Yes I have two VMs with the same id that are in different datastores, so this should actually be fine.
> 
> > Or actually it might be caused by two VMs having the same id, could you please check if that's the case in your system?

Do the datastores have the same name and hostname by any chance?

**Comment by ntimo** [comment]
I found the error and created a MR to fix it :) The variable `pbs_snapshot_vm_count_list` was not reset during the loop and therefore the metrics list for the second datastore contained the VMs from the first one which resulted in the pushgateway error.
